on:
  push:
  workflow_dispatch:

jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: austenstone/copilot-cli@main
        with:
          copilot-token: ${{ secrets.PAT }}
          options: '--screen-reader --no-color'
          prompt: |
            Who are you?

            What is your plan?
            
            What tools do you have? Will you use them?

            Can you test out some github mcp tools?
