on:
  push:
  workflow_dispatch:

jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: austenstone/copilot-cli@main
        with:
          github-token: ${{ secrets.PAT }}
          enable-all-github-mcp-tools: true
          # mcp-config: |
          #   {
          #     "mcpServers": {
          #       "github-mcp-server": {
          #         "type": "http",
          #         "url": "https://api.githubcopilot.com/mcp/",
          #         "headers": {
          #           "Authorization": "Bearer ${{ secrets.PAT }}",
          #           "X-MCP-Toolsets": "*"
          #         },
          #         "tools": ["*"]
          #       }
          #     }
          #   }
          agent: ci-fixer
          prompt: |
            Who are you?

            What is your plan?
            
            What tools do you have? Will you use them?
