on:
  push:
  workflow_dispatch:

jobs:
  copilot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: austenstone/copilot-cli@main
        with:
          github-token: ${{ secrets.PAT }}
          enable-all-github-mcp-tools: true
          # mcp-config: |
          #   {
          #     "mcpServers": {
          #       "github-mcp-server": {
          #         "type": "http",
          #         "url": "https://api.githubcopilot.com/mcp/",
          #         "headers": {
          #           "Authorization": "Bearer ${{ secrets.PAT }}",
          #           "X-MCP-Toolsets": "*"
          #         },
          #         "tools": ["*"]
          #       }
          #     }
          #   }
          agent: ci-fixer
          prompt: |
            Try to experiment with mcp tools available to see what they do and if they work.

            List all tools. multiple times in different formats.

            Tell me the time with #tool:time/*

            Try the github mcp tools. #tool:github-mcp-server/* . Don't use the gh cli, use mcp only.
